#!/bin/sh
set +e
wp wc product create --name='Engine String Bag (Big Logo)' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=19.99 --short_description='This fashionable string bag is made of 100% cotton. It is the perfect size for carrying your everyday essentials.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Bag1.jpg"}, {"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Bag1-1.jpg"}, {"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Bag1-2.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Engine"]}]' || true
wp wc product create --name='Engine String Bag (Small Logos)' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=19.99 --short_description='This fashionable string bag is made of 100% cotton. It is the perfect size for carrying your everyday essentials.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Bag2.jpg"}, {"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Bag2-1.jpg"}, {"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Bag2-2.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Engine"]}]' || true
wp wc product create --name='Brand Buttons' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='Represent your favorite CMS, eCommerce Platform, Website Builder, or Plugin Company in style with a cool pin.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/DE-Pins-4.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Divi", "Engine", "WooCommerce", "WordPress"]}]' || true
wp wc product create --name='Brand Buttons' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=9.99 --description='Rep your love!' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/DE-Pins-1.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Divi"]}]' || true
wp wc product create --name='Brand Buttons - Engine' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=9.99 --description='Rep your love for Engine!' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/DE-Pins-4.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Engine"]}]' || true
wp wc product create --name='Brand Buttons - WooCommerce' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=9.99 --description='Rep your love for WooCommerce!' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/DE-Pins-2.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["WooCommerce"]}]' || true
wp wc product create --name='Brand Buttons - WordPress' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=9.99 --description='Rep your love for WordPress!' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/DE-Pins-3.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["WordPress"]}]' || true
wp wc product create --name=Lanyard --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=9.99 --sale_price=7.99 --short_description='Stop losing your important access keys with a lanyard that is ALMOST as reliable as Engine plugins!' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Lanyard1.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Engine"]}]' || true
wp wc product create --name='Engine Tee' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This comfortable cotton t-shirt that features the Engine logo on the front is perfect for any occasion. The shirt is available in three colors.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-yellow-front.jpg"}, {"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-blue-front.jpg"}, {"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-white-front.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Engine"]}, {"name": "Color", "visible": true, "variation": true, "options": ["Blue", "White", "Yellow"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}]' || true
wp wc product create --name='Engine Tee - Blue, Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-blue-front.jpg"}]' --attributes='[{"name": "Color", "visible": true, "variation": true, "options": ["Blue"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='Engine Tee - White, Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-white-front.jpg"}]' --attributes='[{"name": "Color", "visible": true, "variation": true, "options": ["White"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='Engine Tee - Yellow, Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-yellow-front.jpg"}]' --attributes='[{"name": "Color", "visible": true, "variation": true, "options": ["Yellow"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='Engine Tee - Blue, Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-blue-front.jpg"}]' --attributes='[{"name": "Color", "visible": true, "variation": true, "options": ["Blue"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='Engine Tee - White, Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-white-front.jpg"}]' --attributes='[{"name": "Color", "visible": true, "variation": true, "options": ["White"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='Engine Tee - Yellow, Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-yellow-front.jpg"}]' --attributes='[{"name": "Color", "visible": true, "variation": true, "options": ["Yellow"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='Engine Tee - Blue, Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-blue-front.jpg"}]' --attributes='[{"name": "Color", "visible": true, "variation": true, "options": ["Blue"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='Engine Tee - White, Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-white-front.jpg"}]' --attributes='[{"name": "Color", "visible": true, "variation": true, "options": ["White"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='Engine Tee - Yellow, Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-3-yellow-front.jpg"}]' --attributes='[{"name": "Color", "visible": true, "variation": true, "options": ["Yellow"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name=Tee --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This comfortable cotton t-shirt features the logo on the front and back. It is the perfect tee for any occasion.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-2---front.jpg"}, {"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-2---back.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Divi"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}]' || true
wp wc product create --name='Tee - Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --sale_price=12.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='Tee - Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --sale_price=12.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='Tee - Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --sale_price=12.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='WordPress Tee' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This comfortable cotton t-shirt features the WordPress logo on the front and back. It is the perfect tee for any occasion.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-1---front.jpg"}, {"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Shirt-1---back.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["WordPress"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}]' || true
wp wc product create --name='WordPress Tee - Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --sale_price=12.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='WordPress Tee - Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --sale_price=12.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='WordPress Tee - Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --sale_price=12.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='Mens Hoodie' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This hoodie is a must have for any fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your pride.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Hoodie-2.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Divi"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}]' || true
wp wc product create --name='Mens Hoodie - Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=39.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='Mens Hoodie - Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=34.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='Mens Hoodie - Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=34.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='Dat Engine Life Hoodie - Limited Edition' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This Engine hoodie is a must have for any Engine fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your Engine pride.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Hoodie-1.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Engine"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}]' || true
wp wc product create --name='Dat Engine Life Hoodie - Limited Edition - Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=44.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='Dat Engine Life Hoodie - Limited Edition - Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=44.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='Dat Engine Life Hoodie - Limited Edition - Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=44.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='Mens WordPress Hoodie' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This WordPress hoodie is a must have for any WordPress fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your WordPress pride.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Hoodie-3.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["WordPress"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}]' || true
wp wc product create --name='Mens WordPress Hoodie - Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=34.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='Mens WordPress Hoodie - Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=34.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='Mens WordPress Hoodie - Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=34.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='Engine Logo Zipper Hoodie' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This Engine hoodie is a must have for any Engine fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your Engine pride.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Hoodie-Women-1.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Engine"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}]' || true
wp wc product create --name='Engine Logo Zipper Hoodie - Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=29.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='Engine Logo Zipper Hoodie - Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=29.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='Engine Logo Zipper Hoodie - Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=29.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='Purple Engine Text Zipper Hoodie' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This Engine hoodie is a must have for any Engine fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your Engine pride.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Hoodie-Women-2.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Engine"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}]' || true
wp wc product create --name='Purple Engine Text Zipper Hoodie - Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=29.99 --sale_price=27.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='Purple Engine Text Zipper Hoodie - Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=29.99 --sale_price=27.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='Purple Engine Text Zipper Hoodie - Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=29.99 --sale_price=27.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='WooCommerce "Gimme the Money" Zipper Hoodie' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This WooCommerce hoodie is a must have for any WooCommerce fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your WooCommerce pride.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Hoodie-Women-3.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["WooCommerce"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}]' || true
wp wc product create --name='WooCommerce "Gimme the Money" Zipper Hoodie - Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=29.99 --sale_price=27.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='WooCommerce "Gimme the Money" Zipper Hoodie - Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=29.99 --sale_price=27.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='WooCommerce "Gimme the Money" Zipper Hoodie - Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=29.99 --sale_price=27.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='Ninja Tee' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This comfortable cotton t-shirt features the logo on the front and expresses your Ninja status with the theme. It is the perfect tee for any occasion.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Divi-Ninja.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Divi"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}]' || true
wp wc product create --name='Ninja Tee - Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='Ninja Tee - Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='Ninja Tee - Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='Simplified Crop-top' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This comfortable cotton crop-top features the and Engine logos on the front and back. It is the perfect tee for any occasion.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-white.jpg"}, {"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-blue.jpg"}, {"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-yellow.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Divi", "Engine"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}, {"name": "Color", "visible": true, "variation": true, "options": ["Blue", "White", "Yellow"]}]' || true
wp wc product create --name='Dat Engine Life Crop-top (3-Tone)' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=variable --short_description='This comfortable cotton crop-top features the Engine logo on the front expressing how easy "data Engine life" is. It is the perfect tee for any occasion.' --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/Dat-Divi_Life.jpg"}]' --attributes='[{"name": "Brand", "visible": true, "variation": true, "options": ["Engine"]}, {"name": "Size", "visible": true, "variation": true, "options": ["Large", "Medium", "Small"]}]' || true
wp wc product create --name='Dat Engine Life Crop-top (3-Tone) - Large' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=14.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}]' || true
wp wc product create --name='Dat Engine Life Crop-top (3-Tone) - Medium' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}]' || true
wp wc product create --name='Dat Engine Life Crop-top (3-Tone) - Small' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}]' || true
wp wc product create --name='Simplified Crop-top - Large, Blue' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-blue.jpg"}]' --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}, {"name": "Color", "visible": true, "variation": true, "options": ["Blue"]}]' || true
wp wc product create --name='Simplified Crop-top - Large, White' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-white.jpg"}]' --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}, {"name": "Color", "visible": true, "variation": true, "options": ["White"]}]' || true
wp wc product create --name='Simplified Crop-top - Large, Yellow' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-yellow.jpg"}]' --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Large"]}, {"name": "Color", "visible": true, "variation": true, "options": ["Yellow"]}]' || true
wp wc product create --name='Simplified Crop-top - Medium, Blue' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-blue.jpg"}]' --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}, {"name": "Color", "visible": true, "variation": true, "options": ["Blue"]}]' || true
wp wc product create --name='Simplified Crop-top - Medium, White' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-white.jpg"}]' --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}, {"name": "Color", "visible": true, "variation": true, "options": ["White"]}]' || true
wp wc product create --name='Simplified Crop-top - Medium, Yellow' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-yellow.jpg"}]' --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Medium"]}, {"name": "Color", "visible": true, "variation": true, "options": ["Yellow"]}]' || true
wp wc product create --name='Simplified Crop-top - Small, Blue' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-blue.jpg"}]' --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}, {"name": "Color", "visible": true, "variation": true, "options": ["Blue"]}]' || true
wp wc product create --name='Simplified Crop-top - Small, White' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-white.jpg"}]' --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}, {"name": "Color", "visible": true, "variation": true, "options": ["White"]}]' || true
wp wc product create --name='Simplified Crop-top - Small, Yellow' --user=${WP_ADMIN_USER} --allow-root --status=publish --type=simple --regular_price=12.99 --images='[{"src": "https://ajax-filters-bc.diviengine.com/sampledata/images/divi-Simplified-croptop-yellow.jpg"}]' --attributes='[{"name": "Size", "visible": true, "variation": true, "options": ["Small"]}, {"name": "Color", "visible": true, "variation": true, "options": ["Yellow"]}]' || true
